# oc get ingresscontrollers -n openshift-ingress-operator default -o yaml
# oc edit ingresscontrollers -n openshift-ingress-operator default
apiVersion: operator.openshift.io/v1
kind: IngressController
metadata:
  name: default
  namespace: openshift-ingress-operator
spec:
  replicas: 3